import MainNavBar from "@/components/MainNavBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MainNavBar/>
        {children}
      </body>
    </html>
  );
}

